version: '3.1'
services:
  db:
    image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    #image: mysql:5.6.50
    container_name: my_mysql
    #restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pehape
    #restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "9999:80"
