version: "2.1"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Istanbul
      - INTERFACE=eth0 #optional
    volumes:
      - ~/openvpn-configs:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: always